CREATE TABLE BUYER(ID SERIAL PRIMARY KEY, NAME VARCHAR(50), EMAIL VARCHAR(50), ADDRESS VARCHAR(150), PURCHASEHISTORY JSONB, CART JSONB);

CREATE TABLE ITEM(ID SERIAL PRIMARY KEY, NAME VARCHAR(50), PRICE INT, AVAILABLE BOOL NOT NULL DEFAULT TRUE, SELLERID INT, RATING FLOAT, REVIEWS JSONB, DELIVERYTIME INT);
CREATE TABLE REVIEW(ID SERIAL PRIMARY KEY, ITEMID INT, BUYERID INT, COMMENT VARCHAR(150));
CREATE TABLE SELLER(ID SERIAL PRIMARY KEY, NAME VARCHAR(50), EMAIL VARCHAR(50), ADDRESS VARCHAR(150), TOTALSALES Number, RATING FLOAT);
CREATE TABLE CART(ID SERIAL PRIMARY KEY, ITEMID INT, BUYERID INT, QUANTITY INT);

INSERT INTO weather (date, city, temp_hi, temp_lo)
    VALUES ('1994-11-29', 'Hayward', 54, 37);

INSERT INTO BUYER() VALUES

CREATE TABLE users(ID SERIAL PRIMARY KEY, username VARCHAR(50), password VARCHAR(20));
